In [27]:
import pickle

In [28]:
X = pickle.load(open('X.pkl', 'rb'))
y = pickle.load(open('y.pkl', 'rb'))

In [29]:
X

array([[[  6,   6,   6, ...,   6,   6,   6],
        [  6, 125, 232, ..., 108,  35,   0],
        [  6, 130, 222, ..., 108,  34,   4],
        ...,
        [  6,   6,   6, ...,   6,   6,   6],
        [  6,   6,   6, ...,   6,   6,   6],
        [  6,   6,   6, ...,   6,   6,   6]],

       [[  6,   4,   3, ...,  24,   6,   2],
        [  6,   7,   4, ...,  26,   6,   6],
        [ 15,  25,   6, ...,  14,   4,  15],
        ...,
        [ 93, 102,  77, ...,  79,  75,  61],
        [ 81,  91,  90, ..., 101,  79,  87],
        [ 99, 123,  73, ...,  96,  61,  44]],

       [[123, 133, 130, ..., 164,  50,  77],
        [129, 129, 131, ...,  65,  27,  69],
        [128, 123, 131, ...,  85,  36,  75],
        ...,
        [ 47,  84, 111, ..., 193, 178, 200],
        [ 99,  46,  36, ..., 206, 204, 178],
        [ 65, 120,  54, ..., 203, 208, 224]],

       ...,

       [[128, 177, 183, ..., 114, 128, 118],
        [ 94, 181, 173, ..., 121, 116, 140],
        [100, 166, 179, ..., 138, 147, 152

In [30]:
y

array([0, 1, 0, ..., 1, 0, 0])

In [31]:
X = X/255

In [32]:
X

array([[[0.02352941, 0.02352941, 0.02352941, ..., 0.02352941,
         0.02352941, 0.02352941],
        [0.02352941, 0.49019608, 0.90980392, ..., 0.42352941,
         0.1372549 , 0.        ],
        [0.02352941, 0.50980392, 0.87058824, ..., 0.42352941,
         0.13333333, 0.01568627],
        ...,
        [0.02352941, 0.02352941, 0.02352941, ..., 0.02352941,
         0.02352941, 0.02352941],
        [0.02352941, 0.02352941, 0.02352941, ..., 0.02352941,
         0.02352941, 0.02352941],
        [0.02352941, 0.02352941, 0.02352941, ..., 0.02352941,
         0.02352941, 0.02352941]],

       [[0.02352941, 0.01568627, 0.01176471, ..., 0.09411765,
         0.02352941, 0.00784314],
        [0.02352941, 0.02745098, 0.01568627, ..., 0.10196078,
         0.02352941, 0.02352941],
        [0.05882353, 0.09803922, 0.02352941, ..., 0.05490196,
         0.01568627, 0.05882353],
        ...,
        [0.36470588, 0.4       , 0.30196078, ..., 0.30980392,
         0.29411765, 0.23921569],
        [0.3

In [33]:
X = X.reshape(-1, 60, 60, 1)

In [34]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Dense, Flatten

In [35]:
model = Sequential()

model.add(Conv2D(64, (3,3), activation = 'relu'))
model.add(MaxPooling2D((2,2)))

model.add(Conv2D(64, (3,3), activation = 'relu'))
model.add(MaxPooling2D((2,2)))

model.add(Flatten())

model.add(Dense(128, input_shape = X.shape[1:], activation = 'relu'))

model.add(Dense(2, activation = 'softmax'))

In [36]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [22]:
model.fit(X, y, epochs=5, validation_split=0.1)

Epoch 1/5


563/563 [==============================] - 50s 85ms/step - loss: 0.6571 - accuracy: 0.6016 - val_loss: 0.5907 - val_accuracy: 0.6750
Epoch 2/5
563/563 [==============================] - 49s 87ms/step - loss: 0.5565 - accuracy: 0.7176 - val_loss: 0.5096 - val_accuracy: 0.7540
Epoch 3/5
563/563 [==============================] - 50s 88ms/step - loss: 0.4863 - accuracy: 0.7642 - val_loss: 0.5259 - val_accuracy: 0.7385
Epoch 4/5
563/563 [==============================] - 46s 81ms/step - loss: 0.4355 - accuracy: 0.7952 - val_loss: 0.4747 - val_accuracy: 0.7660
Epoch 5/5
563/563 [==============================] - 45s 80ms/step - loss: 0.3666 - accuracy: 0.8359 - val_loss: 0.4650 - val_accuracy: 0.7865


In [37]:
X.shape

(5000, 60, 60, 1)

In [38]:
import time

time.time()

1707310532.2506883

In [40]:
type(1707310532.2506883)

float